name: gendp
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - xformers
dependencies:
  - python=3.9
  - pip=22.2.2
  - cuda-toolkit=12.1.0
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch3d=0.7.5
  - numpy=1.23.3
  - numba==0.56.4
  - cffi=1.15.1
  - ipykernel=6.16
  - zarr=2.12.0
  - numcodecs=0.10.2
  - h5py=3.7.0
  - hydra-core=1.2.0
  - einops=0.4.1
  - tqdm=4.64.1
  - dill=0.3.5.1
  - scikit-video=1.1.11
  - scikit-image=0.19.3
  - gym=0.21.0
  - pymunk=6.2.1
  - wandb=0.16.1
  - threadpoolctl=3.1.0
  - shapely=1.8.4
  - cython=0.29.32
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - termcolor=2.0.1
  - tensorboard=2.10.1
  - tensorboardx=2.5.1
  - psutil=5.9.2
  - click=8.0.4
  - boto3=1.24.96
  - accelerate=0.13.2
  - datasets=2.6.1
  - diffusers=0.11.1
  - av=10.0.0
  - cmake=3.24.3
  - llvm-openmp=14
  - imagecodecs==2022.8.8
  - xformers
  - pip:
    - imagecodecs==2022.9.26
    - sapien==2.2.2
    - pyperclip==1.8.2
    - open3d==0.18.0
    - plotly==5.17.0
    - PyMCubes==0.1.4
    - trimesh==4.0.0
    - git+https://github.com/facebookresearch/segment-anything.git
    - accelerate==0.20.3
    - scipy==1.9.1
    - matplotlib==3.8.2
    - opencv-contrib-python==4.9.0.80
    - git+https://github.com/WangYixuan12/GroundingDINO.git
    - gdown==4.7.1
    - urchin==0.0.27 # urdfpy
    - pyrealsense2==2.54.2.5684
    - atomics==1.0.2
    - pynput==1.6.0
    - pybullet==3.2.6
    - rospkg==1.5.1
    - modern_robotics==1.1.1
